version: '3.2'
services:
  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - "80:80"
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./data/html:/var/www/html

  bookstore-db:
    image: mysql:5.7.22
    volumes:
      - ./data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  flyway_clean:
    image: boxfuse/flyway:5.0.7-alpine
    volumes:
      - ../flyway/sql:/flyway/sql
      - ../flyway/conf:/flyway/conf
    command: -configFiles=conf/flyway.local.conf clean
    depends_on:
      - bookstore-db

  flyway_migrate:
    image: boxfuse/flyway:5.0.7-alpine
    volumes:
      - ../flyway/sql:/flyway/sql
      - ../flyway/conf:/flyway/conf
    command: -configFiles=conf/flyway.local.conf migrate
    depends_on:
      - bookstore-db

